name: 'Setup Node.js with Cache'
description: 'Setup Node.js with npm cache and install dependencies'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: 'v22.19.0'
  working-directory:
    description: 'Working directory for npm operations'
    required: false
    default: '.'
  cache-dependency-path:
    description: 'Path to pnpm-lock.yaml for cache key'
    required: false
    default: 'pnpm-lock.yaml'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  registry:
    description: 'npm registry to use'
    required: false
    default: 'https://registry.npmjs.org/'
  project:
    description: 'Project to filter for installation (pnpm --filter). Leave empty to install everything.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        registry-url: ${{ inputs.registry }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -z "${{ inputs.project }}" ]; then
          pnpm install --registry=${{ inputs.registry }}
        else
          pnpm install --filter=${{ inputs.project }} --registry=${{ inputs.registry }}
        fi
