packages:
  # Main applications
  - 'server'
  - 'client'
  - 'cron'

  # Supporting applications
  - 'scripts'
  - 'mock-server'
  
  # Test packages
  - 'tests/e2e-tests'
  - 'tests/integration-tests'
  
  # Shared packages
  - '@my-dashboard/types'
  - '@my-dashboard/sdk'
