[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["cron/**"]

[source]
repo = "jayc13/my-dashboard"
branch = "main"
rootDirectory = "cron"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
cronJobsEnabled = true
numReplicas = 1

[deploy.resources]
cpu = 1
memory = 1

[environments.production.variables]
NODE_ENV = "production"
