[build]
buildCommand = "./scripts/deployment/railway-cron-build.sh"
watchPatterns = ["cron/**","pnpm-lock.yaml"]

[source]
repo = "jayc13/my-dashboard"
branch = "main"
rootDirectory = ""

[deploy]
startCommand = "cd cron && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
cronJobsEnabled = true
numReplicas = 1

[deploy.resources]
cpu = 1
memory = 1

[environments.production.variables]
NODE_ENV = "production"
