import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    homeSidebar: [
        {
            type: "doc",
            id: "index", // document ID
            label: 'Home'
        },
        'getting-started',
      {
        type: 'category',
        label: 'Architecture',
        items: [{type: 'autogenerated', dirName: 'architecture'}],
      },
      {
        type: 'category',
        label: 'Development Guides',
        items: [{type: 'autogenerated', dirName: 'development'}],
      },
      {
        type: 'category',
        label: 'TypeScript SDK',
        items: [{type: 'autogenerated', dirName: 'sdk'}],
      },
      {
        type: 'category',
        label: 'API Reference',
        items: [{type: 'autogenerated', dirName: 'api'}],
      },
      {
        type: 'category',
        label: 'Others',
        items: [{type: 'autogenerated', dirName: 'others'}],
      }
    ],
};

export default sidebars;
