#!/usr/bin/env sh

echo "🔍 Running pre-commit checks..."

for dir in client server cron scripts; do
  cd "$(git rev-parse --show-toplevel)" || exit
  cd "./$dir" || exit
  # Install dependencies to avoid problems with dependencies
  echo "📦 Installing dependencies in $dir..."
  npm install --registry=https://registry.npmjs.org/
  # Run linting
  echo "📝 Running linting in $dir..."
  npm run lint

  # If linting passes, run lint:fix to auto-fix issues
  if [ $? -eq 0 ]; then
    echo "✅ Linting passed in $dir! Running auto-fix..."
    npm run lint-fix
  else
    echo "❌ Linting failed in $dir! Please fix the issues before committing."
    exit 1
  fi
done

echo "✅ Pre-commit checks completed successfully!"
