name: Pull Request Validation

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened, ready_for_review ]

# Cancel in-progress runs for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  # Job 1: Basic validation and setup
  basic-validation:
    name: Basic Validation
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/basic-validation.yml
    with:
      pr-title: ${{ github.event.pull_request.title }}
      base-sha: ${{ github.event.pull_request.base.sha }}
      head-sha: ${{ github.event.pull_request.head.sha }}

  # Job 2: Client validation
  validate-client:
    name: Validate Client
    needs: basic-validation
    if: needs.basic-validation.outputs.client-changed == 'true' || needs.basic-validation.outputs.github-changed == 'true'
    uses: ./.github/workflows/validate-client.yml

  # Job 3: Server validation
  validate-server:
    name: Validate Server
    needs: basic-validation
    if: needs.basic-validation.outputs.server-changed == 'true' || needs.basic-validation.outputs.github-changed == 'true'
    uses: ./.github/workflows/validate-server.yml

  # Job 4: Cron validation
  validate-cron:
    name: Validate Cron
    needs: basic-validation
    if: needs.basic-validation.outputs.cron-changed == 'true' || needs.basic-validation.outputs.github-changed == 'true'
    uses: ./.github/workflows/validate-cron.yml

  # Job 5: Scripts validation
  validate-scripts:
    name: Validate Scripts
    needs: basic-validation
    if: needs.basic-validation.outputs.scripts-changed == 'true' || needs.basic-validation.outputs.github-changed == 'true'
    uses: ./.github/workflows/validate-scripts.yml

  # Job 6: Final validation and summary
  validation-summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [ basic-validation, validate-client, validate-server, validate-cron, validate-scripts ]
    if: always()
    steps:
      - name: Check all validations
        run: |
          echo "=== Pull Request Validation Summary ==="
          echo "Basic validation: ${{ needs.basic-validation.result }}"
          echo "Client validation: ${{ needs.validate-client.result }}"
          echo "Server validation: ${{ needs.validate-server.result }}"
          echo "Cron validation: ${{ needs.validate-cron.result }}"
          echo "Scripts validation: ${{ needs.validate-scripts.result }}"

          # Fail if any required job failed
          if [[ "${{ needs.basic-validation.result }}" == "failure" ]] || \
             [[ "${{ needs.validate-client.result }}" == "failure" ]] || \
             [[ "${{ needs.validate-server.result }}" == "failure" ]] || \
             [[ "${{ needs.validate-cron.result }}" == "failure" ]] || \
             [[ "${{ needs.validate-scripts.result }}" == "failure" ]]; then
            echo "❌ One or more validations failed"
            exit 1
          else
            echo "✅ All validations passed"
          fi

      - name: Comment on PR
        if: always()
        run: |
          echo "TODO: Implement PR commenting"
          echo "TODO: Post validation results as PR comment"
          echo "TODO: Include links to failed checks and suggestions"
