name: 'Validate Server'

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory for server operations'
        required: false
        type: string
        default: './server'
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: 'v22.20.0'

jobs:
  validate-server:
    name: Validate Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ github.workspace }}

      - name: Build @my-dashboard/types
        run: pnpm --filter=@my-dashboard/types run build
        working-directory: ${{ github.workspace }}

      - name: Type check
        run: pnpm --filter=server run typecheck

      - name: Run linting
        run: pnpm --filter=server run lint

      - name: Build server
        run: pnpm --filter=server run build

      - name: Test database migrations
        env:
          NODE_ENV: test
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: test_password
          MYSQL_DATABASE: test_db
        run: pnpm --filter=server run migrate

      - name: Run unit tests
        env:
          NODE_ENV: test
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: test_password
          MYSQL_DATABASE: test_db
        run: pnpm --filter=server run test
