name: 'Validate Cron'

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory for cron operations'
        required: false
        type: string
        default: './cron'
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: 'v22.20.0'

jobs:
  validate-cron:
    name: Validate Cron
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ github.workspace }}

      - name: Build @my-dashboard/types
        run: pnpm --filter=@my-dashboard/types run build
        working-directory: ${{ github.workspace }}

      - name: Type check
        run: pnpm --filter=cron run typecheck

      - name: Run linting
        run: pnpm --filter=cron run lint

      - name: Build cron
        run: pnpm --filter=cron run build

      - name: Run tests
        run: |
          echo "TODO: Implement cron job tests"
          echo "TODO: Add unit tests for cron job logic"
          echo "TODO: Test cron schedule validation"

      - name: Validate cron configuration
        run: |
          echo "TODO: Implement cron configuration validation"
          echo "TODO: Validate cron expressions"
          echo "TODO: Check for proper error handling"
