name: 'Validate Client'

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory for client operations'
        required: false
        type: string
        default: './client'
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: 'v22.20.0'
      run-bundle-analysis:
        description: 'Whether to run bundle size analysis'
        required: false
        type: boolean
        default: true

jobs:
  validate-client:
    name: Validate Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ github.workspace }}

      - name: Build dependencies
        run: |
          pnpm --filter=@my-dashboard/types run build
          pnpm --filter=@my-dashboard/sdk run build
        working-directory: ${{ github.workspace }}

      - name: Run ESLint
        run: pnpm --filter=client run lint

      - name: Type check
        run: pnpm --filter=client run typecheck

      - name: Build client
        run: pnpm --filter=client run build

      - name: Run unit tests
        run: pnpm --filter=client run test
